version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api